//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MileageStats.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MileageStats.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the properties must have a value..
        /// </summary>
        public static string AtLeastOneNonNullPropertyValidationAttribute_IsValid_OnePropertyMustHaveValue {
            get {
                return ResourceManager.GetString("AtLeastOneNonNullPropertyValidationAttribute_IsValid_OnePropertyMustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string AuthController_CreateOrGetUser_New_User {
            get {
                return ResourceManager.GetString("AuthController_CreateOrGetUser_New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to authenticate you with provider at this time.  Please check your provider URL and try again..
        /// </summary>
        public static string AuthController_SignIn_UnableToAuthenticateWithProvider {
            get {
                return ResourceManager.GetString("AuthController_SignIn_UnableToAuthenticateWithProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate at this time..
        /// </summary>
        public static string AuthController_SignInResponse_Unable_to_authenticate {
            get {
                return ResourceManager.GetString("AuthController_SignInResponse_Unable_to_authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find vehicle to update..
        /// </summary>
        public static string CannotFindVehicleToUpdateExceptionMessage {
            get {
                return ResourceManager.GetString("CannotFindVehicleToUpdateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Fuel Efficiency.
        /// </summary>
        public static string ChartController_AverageFuelEfficiencyChart_Title {
            get {
                return ResourceManager.GetString("ChartController_AverageFuelEfficiencyChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string ChartController_TotalCost_Title {
            get {
                return ResourceManager.GetString("ChartController_TotalCost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Distance.
        /// </summary>
        public static string ChartController_TotalDistance_Title {
            get {
                return ResourceManager.GetString("ChartController_TotalDistance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The due distance must be greater than the current odometer of {0}..
        /// </summary>
        public static string DueDistanceNotGreaterThanOdometer {
            get {
                return ResourceManager.GetString("DueDistanceNotGreaterThanOdometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Per Unit.
        /// </summary>
        public static string FillupEntryCostPerUnitLabelText {
            get {
                return ResourceManager.GetString("FillupEntryCostPerUnitLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required..
        /// </summary>
        public static string FillupEntryDateRequired {
            get {
                return ResourceManager.GetString("FillupEntryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Efficiency.
        /// </summary>
        public static string FillupEntryFuelEfficiencyLabelText {
            get {
                return ResourceManager.GetString("FillupEntryFuelEfficiencyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The odometer must be between 1 and 1,000,000..
        /// </summary>
        public static string FillupEntryOdometerRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryOdometerRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer is required..
        /// </summary>
        public static string FillupEntryOdometerRequired {
            get {
                return ResourceManager.GetString("FillupEntryOdometerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Unit (ex. 3.75).
        /// </summary>
        public static string FillupEntryPricePerUnitLabelText {
            get {
                return ResourceManager.GetString("FillupEntryPricePerUnitLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price per gallon must be between 0.1 and 100..
        /// </summary>
        public static string FillupEntryPricePerUnitRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryPricePerUnitRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per unit is required..
        /// </summary>
        public static string FillupEntryPricePerUnitRequired {
            get {
                return ResourceManager.GetString("FillupEntryPricePerUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks must be fewer than 250 characters..
        /// </summary>
        public static string FillupEntryRemarksStringLengthValidationError {
            get {
                return ResourceManager.GetString("FillupEntryRemarksStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost.
        /// </summary>
        public static string FillupEntryTotalCostLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTotalCostLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fuel Cost.
        /// </summary>
        public static string FillupEntryTotalFuelCostLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTotalFuelCostLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Units (ex. 10.123).
        /// </summary>
        public static string FillupEntryTotalUnitsLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTotalUnitsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total gallons must be between 1 and 1000..
        /// </summary>
        public static string FillupEntryTotalUnitsRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryTotalUnitsRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total units are required..
        /// </summary>
        public static string FillupEntryTotalUnitsRequired {
            get {
                return ResourceManager.GetString("FillupEntryTotalUnitsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Fee (ex. 0.45).
        /// </summary>
        public static string FillupEntryTransactionFeeLabelText {
            get {
                return ResourceManager.GetString("FillupEntryTransactionFeeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction fee must be between 0 and 100..
        /// </summary>
        public static string FillupEntryTransactionFeeRangeValidationError {
            get {
                return ResourceManager.GetString("FillupEntryTransactionFeeRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction fee is required..
        /// </summary>
        public static string FillupEntryTransactionFeeRequired {
            get {
                return ResourceManager.GetString("FillupEntryTransactionFeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measure.
        /// </summary>
        public static string FillupEntryUnitOfMeasureLabelText {
            get {
                return ResourceManager.GetString("FillupEntryUnitOfMeasureLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of measure is required..
        /// </summary>
        public static string FillUpEntryUnitOfMeasureRequired {
            get {
                return ResourceManager.GetString("FillUpEntryUnitOfMeasureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill up Station.
        /// </summary>
        public static string FillUpEntryVendorLabelText {
            get {
                return ResourceManager.GetString("FillUpEntryVendorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill up station must be fewer than 20 characters..
        /// </summary>
        public static string FillupEntryVendorStringLengthValidationError {
            get {
                return ResourceManager.GetString("FillupEntryVendorStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date must be a date in the future..
        /// </summary>
        public static string FutureDateValidationMessage {
            get {
                return ResourceManager.GetString("FutureDateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[\d\w]{0,10}$.
        /// </summary>
        public static string InternationalPostalCodeRegex {
            get {
                return ResourceManager.GetString("InternationalPostalCodeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal codes must be alphanumeric and ten characters or less..
        /// </summary>
        public static string InternationalPostalCodeValidationErrorMessage {
            get {
                return ResourceManager.GetString("InternationalPostalCodeValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters and [.,_-&apos;] are allowed..
        /// </summary>
        public static string InvalidInputCharacter {
            get {
                return ResourceManager.GetString("InvalidInputCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters, new lines, and [.,_-&apos;] are allowed..
        /// </summary>
        public static string InvalidMultilineInput {
            get {
                return ResourceManager.GetString("InvalidMultilineInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded for vehicle photo is not an image or is not a supported image format..
        /// </summary>
        public static string InvalidVehiclePhoto {
            get {
                return ResourceManager.GetString("InvalidVehiclePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUserDefaultDisplayName {
            get {
                return ResourceManager.GetString("NewUserDefaultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The odometer must be greater than the prior value of {0}..
        /// </summary>
        public static string OdometerNotGreaterThanPrior {
            get {
                return ResourceManager.GetString("OdometerNotGreaterThanPrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date can not be in the future..
        /// </summary>
        public static string PastDateValidationMessage {
            get {
                return ResourceManager.GetString("PastDateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string ReminderDueDateLabelText {
            get {
                return ResourceManager.GetString("ReminderDueDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due when odometer reads.
        /// </summary>
        public static string ReminderDueDistanceLabelText {
            get {
                return ResourceManager.GetString("ReminderDueDistanceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The odometer due distance must be between 1 and 1,000,000..
        /// </summary>
        public static string ReminderDueDistanceRangeValidationError {
            get {
                return ResourceManager.GetString("ReminderDueDistanceRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks must be fewer than 250 characters..
        /// </summary>
        public static string ReminderRemarksStringLengthValidationError {
            get {
                return ResourceManager.GetString("ReminderRemarksStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string ReminderTitleRequired {
            get {
                return ResourceManager.GetString("ReminderTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be fewer than 50 characters..
        /// </summary>
        public static string ReminderTitleStringLengthValidationError {
            get {
                return ResourceManager.GetString("ReminderTitleStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be between {0:d} and {1:d}..
        /// </summary>
        public static string StoreRestrictedDateValidationMessage {
            get {
                return ResourceManager.GetString("StoreRestrictedDateValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)[A-Za-z0-9\.,&apos;_ \-]*$.
        /// </summary>
        public static string TextLineInputValidatorRegEx {
            get {
                return ResourceManager.GetString("TextLineInputValidatorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?!.*--)([A-Za-z0-9\.,&apos;_ \-]|\r|\n)*$.
        /// </summary>
        public static string TextMultilineValidatorRegEx {
            get {
                return ResourceManager.GetString("TextMultilineValidatorRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of vehicles is 10..
        /// </summary>
        public static string TooManyVehicles {
            get {
                return ResourceManager.GetString("TooManyVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add fill up to vehicle..
        /// </summary>
        public static string UnableToAddFillupToVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddFillupToVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add reminder to vehicle..
        /// </summary>
        public static string UnableToAddReminderToVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToAddReminderToVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create user.
        /// </summary>
        public static string UnableToCreateUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCreateUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create vehicle..
        /// </summary>
        public static string UnableToCreateVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToCreateVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete reminder..
        /// </summary>
        public static string UnableToDeleteReminder {
            get {
                return ResourceManager.GetString("UnableToDeleteReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete vehicle.
        /// </summary>
        public static string UnableToDeleteVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToDeleteVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find user.
        /// </summary>
        public static string UnableToFindUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToFindUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fulfill reminder..
        /// </summary>
        public static string UnableToFulfillReminder {
            get {
                return ResourceManager.GetString("UnableToFulfillReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve countries and regions list..
        /// </summary>
        public static string UnableToGetCountryListExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetCountryListExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get vehicles..
        /// </summary>
        public static string UnableToGetVehiclesExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToGetVehiclesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve fill up information.
        /// </summary>
        public static string UnableToRetireveFillupsExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetireveFillupsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve fulfilled reminders.
        /// </summary>
        public static string UnableToRetrieveFulfilledReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveFulfilledReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve overdue reminders..
        /// </summary>
        public static string UnableToRetrieveOverdueReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveOverdueReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retieve reminder..
        /// </summary>
        public static string UnableToRetrieveReminderExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToRetrieveReminderExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve service history..
        /// </summary>
        public static string UnableToRetrieveServiceHistory {
            get {
                return ResourceManager.GetString("UnableToRetrieveServiceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve unfulfilled reminders.
        /// </summary>
        public static string UnableToRetrieveUnfulfilledReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveUnfulfilledReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve upcoming reminders.
        /// </summary>
        public static string UnableToRetrieveUpcomingReminders {
            get {
                return ResourceManager.GetString("UnableToRetrieveUpcomingReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve vehicle photo..
        /// </summary>
        public static string UnableToRetrieveVehiclePhoto {
            get {
                return ResourceManager.GetString("UnableToRetrieveVehiclePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update user..
        /// </summary>
        public static string UnableToUpdateUserExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update vehicle.
        /// </summary>
        public static string UnableToUpdateVehicleExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateVehicleExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update vehicle sort order..
        /// </summary>
        public static string UnableToUpdateVehicleSortOrderExceptionMessage {
            get {
                return ResourceManager.GetString("UnableToUpdateVehicleSortOrderExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        public static string UnitedStatesDisplayString {
            get {
                return ResourceManager.GetString("UnitedStatesDisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to update the reminder.
        /// </summary>
        public static string UpdateReminderUnauthorized {
            get {
                return ResourceManager.GetString("UpdateReminderUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenID Url.
        /// </summary>
        public static string UserAuthorizationIdLabelText {
            get {
                return ResourceManager.GetString("UserAuthorizationIdLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization ID is required..
        /// </summary>
        public static string UserAuthorizationIdRequired {
            get {
                return ResourceManager.GetString("UserAuthorizationIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country or Region.
        /// </summary>
        public static string UserCountryLabelText {
            get {
                return ResourceManager.GetString("UserCountryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country must be less than 50 characters..
        /// </summary>
        public static string UserCountryStringLengthValidationError {
            get {
                return ResourceManager.GetString("UserCountryStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserDisplayNameLabelText {
            get {
                return ResourceManager.GetString("UserDisplayNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string UserDisplayNameRequired {
            get {
                return ResourceManager.GetString("UserDisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than 15 characters..
        /// </summary>
        public static string UserDisplayNameStringLengthValidationError {
            get {
                return ResourceManager.GetString("UserDisplayNameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added fill up.
        /// </summary>
        public static string VehicleController_AddFillupSuccessMessage {
            get {
                return ResourceManager.GetString("VehicleController_AddFillupSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The odometer must be greater than the prior value of {0}..
        /// </summary>
        public static string VehicleController_ValidateCanAdd_OdometerGreaterThanPrior {
            get {
                return ResourceManager.GetString("VehicleController_ValidateCanAdd_OdometerGreaterThanPrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add vehicle.  The maximum number of vehciles is 10..
        /// </summary>
        public static string VehicleController_ValidateCreate_TooManyVehicles {
            get {
                return ResourceManager.GetString("VehicleController_ValidateCreate_TooManyVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded for vehicle photo is not an image or is not a supported image format..
        /// </summary>
        public static string VehicleController_ValidatePhoto_NotAPhoto {
            get {
                return ResourceManager.GetString("VehicleController_ValidatePhoto_NotAPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo uploaded must be less than 1MB (1048576 bytes).
        /// </summary>
        public static string VehicleController_ValidatePhoto_TooLarge {
            get {
                return ResourceManager.GetString("VehicleController_ValidatePhoto_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make is not valid..
        /// </summary>
        public static string VehicleMakeInvalid {
            get {
                return ResourceManager.GetString("VehicleMakeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string VehicleMakeLabelText {
            get {
                return ResourceManager.GetString("VehicleMakeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make must be less than 50 characters..
        /// </summary>
        public static string VehicleMakeStringLengthValidationError {
            get {
                return ResourceManager.GetString("VehicleMakeStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing make for specified model..
        /// </summary>
        public static string VehicleMissingMakeForModel {
            get {
                return ResourceManager.GetString("VehicleMissingMakeForModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing year for specified make..
        /// </summary>
        public static string VehicleMissingYearForMake {
            get {
                return ResourceManager.GetString("VehicleMissingYearForMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing year for specified model..
        /// </summary>
        public static string VehicleMissingYearForModel {
            get {
                return ResourceManager.GetString("VehicleMissingYearForModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is not valid..
        /// </summary>
        public static string VehicleModelInvalid {
            get {
                return ResourceManager.GetString("VehicleModelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string VehicleModelLabelText {
            get {
                return ResourceManager.GetString("VehicleModelLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model must be less than 50 characters..
        /// </summary>
        public static string VehicleModelStringLengthValidationError {
            get {
                return ResourceManager.GetString("VehicleModelStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name.
        /// </summary>
        public static string VehicleNameLabelText {
            get {
                return ResourceManager.GetString("VehicleNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string VehicleNameRequired {
            get {
                return ResourceManager.GetString("VehicleNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be less than 20 characters..
        /// </summary>
        public static string VehicleNameStringLengthValidationError {
            get {
                return ResourceManager.GetString("VehicleNameStringLengthValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle was not found..
        /// </summary>
        public static string VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image MIME type is required..
        /// </summary>
        public static string VehiclePhotoImageMimeTypeRequired {
            get {
                return ResourceManager.GetString("VehiclePhotoImageMimeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is required..
        /// </summary>
        public static string VehiclePhotoImageRequired {
            get {
                return ResourceManager.GetString("VehiclePhotoImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo uploaded must be less than 1 MB..
        /// </summary>
        public static string VehiclePhotoTooLarge {
            get {
                return ResourceManager.GetString("VehiclePhotoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string VehicleSortOrderLabelText {
            get {
                return ResourceManager.GetString("VehicleSortOrderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sort order must be between 0 and 10,000..
        /// </summary>
        public static string VehicleSortOrderRangeValidationError {
            get {
                return ResourceManager.GetString("VehicleSortOrderRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year is not valid..
        /// </summary>
        public static string VehicleYearInvalid {
            get {
                return ResourceManager.GetString("VehicleYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string VehicleYearLabelText {
            get {
                return ResourceManager.GetString("VehicleYearLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year must be between 1900 and 2100..
        /// </summary>
        public static string VehicleYearRangeValidationError {
            get {
                return ResourceManager.GetString("VehicleYearRangeValidationError", resourceCulture);
            }
        }
    }
}
