//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MileageStats.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MileageStats.Web.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled authentication.
        /// </summary>
        public static string AuthController_CanceledAuthentication {
            get {
                return ResourceManager.GetString("AuthController_CanceledAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string AuthController_CreateOrGetUser_New_User {
            get {
                return ResourceManager.GetString("AuthController_CreateOrGetUser_New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to authenticate you with provider at this time. If you provided your own OpenID URL, please check the URL and try again..
        /// </summary>
        public static string AuthController_SignIn_UnableToAuthenticateWithProvider {
            get {
                return ResourceManager.GetString("AuthController_SignIn_UnableToAuthenticateWithProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate at this time..
        /// </summary>
        public static string AuthController_SignInResponse_Unable_to_authenticate {
            get {
                return ResourceManager.GetString("AuthController_SignInResponse_Unable_to_authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added fill up..
        /// </summary>
        public static string FillupController_FillupAddedMessage {
            get {
                return ResourceManager.GetString("FillupController_FillupAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is invalid..
        /// </summary>
        public static string FillupController_InvalidDate {
            get {
                return ResourceManager.GetString("FillupController_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle not found..
        /// </summary>
        public static string FillupController_VehicleNotFound {
            get {
                return ResourceManager.GetString("FillupController_VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix invalid data..
        /// </summary>
        public static string PleaseFixInvalidData {
            get {
                return ResourceManager.GetString("PleaseFixInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request Data.
        /// </summary>
        public static string ProfileController_InvalidData {
            get {
                return ResourceManager.GetString("ProfileController_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated profile..
        /// </summary>
        public static string ProfileController_ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileController_ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to execute this action over the reminder..
        /// </summary>
        public static string Reminder_ForbiddenAction {
            get {
                return ResourceManager.GetString("Reminder_ForbiddenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is invalid..
        /// </summary>
        public static string ReminderController_InvalidDate {
            get {
                return ResourceManager.GetString("ReminderController_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added reminder..
        /// </summary>
        public static string ReminderController_ReminderAdded {
            get {
                return ResourceManager.GetString("ReminderController_ReminderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted reminder..
        /// </summary>
        public static string ReminderController_ReminderDeleted {
            get {
                return ResourceManager.GetString("ReminderController_ReminderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully fulfilled reminder..
        /// </summary>
        public static string ReminderController_ReminderFulfilled {
            get {
                return ResourceManager.GetString("ReminderController_ReminderFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle not found..
        /// </summary>
        public static string ReminderController_VehicleNotFound {
            get {
                return ResourceManager.GetString("ReminderController_VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added vehicle..
        /// </summary>
        public static string VehicleController_VehicleAdded {
            get {
                return ResourceManager.GetString("VehicleController_VehicleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted vehicle..
        /// </summary>
        public static string VehicleController_VehicleDeleted {
            get {
                return ResourceManager.GetString("VehicleController_VehicleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle not found..
        /// </summary>
        public static string VehicleController_VehicleNotFound {
            get {
                return ResourceManager.GetString("VehicleController_VehicleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated vehicle..
        /// </summary>
        public static string VehicleController_VehicleUpdated {
            get {
                return ResourceManager.GetString("VehicleController_VehicleUpdated", resourceCulture);
            }
        }
    }
}
